version: 2

services:

  calculadora-investimentos:
    image: maven
    volumes: 
     - ".:/deploy"
    working_dir: "/deploy"
    ports: 
     - "8080:8080"
    command: bash -c "mvn clean compile package && java -jar target/calculadora-investimentos.jar"
    container_name: calculadora-investimentos